services:
  - type: web
    name: portfolio-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORTFOLIO_URL
        sync: false
      - key: DASHBOARD_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRES
        sync: false
      - key: COOKIE_EXPIRE
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SERVICE
        sync: false
      - key: SMTP_MAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
